In [10]:
%matplotlib inline
import pandas as pd
import numpy as np
import ipywidgets as widgets
from ipywidgets import interactive
import datetime
from datetime import date, timedelta
from IPython.display import HTML
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [6]:
HTML('''<script>
  function code_toggle() {
    if (code_shown){
      $('div.input').hide('500');
      $('#toggleButton').val('Show Code')
    } else {
      $('div.input').show('500');
      $('#toggleButton').val('Hide Code')
    }
    code_shown = !code_shown
  }

  $( document ).ready(function(){
    code_shown=false;
    $('div.input').hide()
  });
</script>
<form action="javascript:code_toggle()"><input type="submit" id="toggleButton" value="Show Code"></form>''')

In [13]:
result = pd.read_csv('/Users/ryan/Desktop/baseline/notebook/baseline_data_for_viewer.csv', header=0, dtype= 'unicode', parse_dates=['date'])   
enum_names = pd.read_csv('/Users/ryan/Downloads/enum_list_baseline_MAY17 (Autosaved).csv',header=0, dtype= 'unicode')

result.loc[result['dod_enumerator_id_intro'] == "amirulislamo4416@gmail.com" ,'dod_enumerator_id_intro'] = "amirulislam04416@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "deepakkharte@gmail.com" ,'dod_enumerator_id_intro'] = "deepakkharte14@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "jagdishpawar1983@rediffmail.com" ,'dod_enumerator_id_intro'] = "pawarjagdish1983@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "jagdishpawar1983@rediffmail.com" ,'dod_enumerator_id_intro'] = "pawarjagdish1983@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "kumarvikash5055@gmail.com" ,'dod_enumerator_id_intro'] = "vikashkrsah51@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "kundan9570dod@gmail.com" ,'dod_enumerator_id_intro'] = "kundan957dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "modaser@gmail.com" ,'dod_enumerator_id_intro'] = "modasder@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "rahul.rawelcom@gmail.com" ,'dod_enumerator_id_intro'] = "rahulkumarjha.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "ramesh.chandra@rain-drop.org" ,'dod_enumerator_id_intro'] = "rameshchandra.ssa1980@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "shahmanoj519@gmail" ,'dod_enumerator_id_intro'] = "shahmanoj519@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "tharshit290@gmail.com" ,'dod_enumerator_id_intro'] = "tharshit190@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "wasimansarihrp@gmail.com" ,'dod_enumerator_id_intro'] = "wasimansari.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "Lalitpanwargm@gmail.com" ,'dod_enumerator_id_intro'] = "lalitpanwargm@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "manojmurmu.dod@gmail.co" ,'dod_enumerator_id_intro'] = "manojmurmu.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mdas88644@giml.co" ,'dod_enumerator_id_intro'] = "mdas88644@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mantoshkumar.dod7654@gmil.come" ,'dod_enumerator_id_intro'] = "mantoshkumar.dod7654@gmil.com"
result.loc[result['dod_enumerator_id_intro'] == "jitendrakmr.singh8294@gmail.com0" ,'dod_enumerator_id_intro'] = "jitendrakmr.singh8294@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "ashokkumar.dod96@gmail.comA" ,'dod_enumerator_id_intro'] = "ashokkumar.dod96@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "dilipkumar1993@gmail.come" ,'dod_enumerator_id_intro'] = "dilipkumar1993@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mantoshkumar.dod7654@gmil.com" ,'dod_enumerator_id_intro'] = "mantoshkumar.dod7654@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mdas88644@giml.com" ,'dod_enumerator_id_intro'] = "mdas88644@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "djbhaskar@gmail.com" ,'dod_enumerator_id_intro'] = "djbhaskar92@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "Dodhayat91221@gmail.com" ,'dod_enumerator_id_intro'] = "dodhayat91221@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "pujaroy087@gmail.com" ,'dod_enumerator_id_intro'] = "pujapujaroy087@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "Dodmunna1990@gmail.com" ,'dod_enumerator_id_intro'] = "dodmunna1990@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "kdm6451@gmail.com" ,'dod_enumerator_id_intro'] = "kdm6451@gmail.com "
result.loc[result['dod_enumerator_id_intro'] == "ankeshkumarmandaldod.@gmail.com" ,'dod_enumerator_id_intro'] = "ankeshnirala7151@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "SabitaKumari.dod@gmail.com" ,'dod_enumerator_id_intro'] = "sabitaKumari.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "latumanib@gmail.com" ,'dod_enumerator_id_intro'] = "latumanibarman78@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "tiroshrabha@gmail.com" ,'dod_enumerator_id_intro'] = "tiroshrabha73@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "rahmanatikur470@gmail.com" ,'dod_enumerator_id_intro'] = "rahmanatikur470@gmail.com"


result = result.merge(enum_names,how='left', on = 'dod_enumerator_id_intro')


#generating Productivity Tables
result['complete'] = pd.to_numeric(result['complete'], errors='coerce')
result['hh_size_hhinfo'] = pd.to_numeric(result['hh_size_hhinfo'], errors='coerce')
result['incomplete'] = pd.to_numeric(result['incomplete'], errors='coerce')
result['perm_unavail'] = pd.to_numeric(result['perm_unavail'], errors='coerce')
result['refusal'] = pd.to_numeric(result['refusal'], errors='coerce')

In [14]:
table = result[['state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).count()
table['Total Attempted'] = result[['scto_uuid', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).count()
table['Total Refusals'] = result[['refusal', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).sum()
table['Total Permanently Unavailable'] = result[['perm_unavail', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).sum()
table['Total Incomplete'] = result[['incomplete', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).sum()
table['Total Complete'] = result[['complete', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).sum()

table = table.reset_index()

In [15]:
yesterday = date.today() - timedelta(1)
yesterday = yesterday.strftime('%Y-%m-%d')
daily_result =  result.loc[result['date'].astype(str) == yesterday]

table_today = daily_result[['state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).count()
table_today['Attempted YESTERDAY'] = daily_result[['scto_uuid', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).count()
table_today['Incomplete YESTERDAY'] = daily_result[['incomplete', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).sum()
table_today['Complete YESTERDAY'] = daily_result[['complete', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).sum()

table_today = table_today.reset_index()
table=table.merge(table_today,how='outer',on=['enum_name', 'state_name', 'dist_name'])
table.fillna(0, inplace=True)
table = table[['dist_name','enum_name', 'Total Attempted', 'Attempted YESTERDAY', 'Total Complete', 'Complete YESTERDAY', 'Total Incomplete', 'Incomplete YESTERDAY','Total Refusals','Total Permanently Unavailable']]
table

,dist_name,enum_name,Total Attempted,Attempted YESTERDAY,Total Complete,Complete YESTERDAY,Total Incomplete,Incomplete YESTERDAY,Total Refusals,Total Permanently Unavailable
0,BAKSA,ASHOK KUMAR,19,3.0,15.0,2.0,4,1.0,0,0
1,BAKSA,ATIKUR RAHMAN,19,3.0,15.0,2.0,4,1.0,0,0
2,BAKSA,CHAMPAK DAS,14,3.0,7.0,0.0,3,1.0,1,3
3,BAKSA,DEEPJYOTI DEKA,17,4.0,14.0,3.0,3,1.0,0,0
4,BAKSA,DIGANTA DAS,23,2.0,13.0,0.0,10,2.0,0,0
5,BAKSA,GAGAN BARMAN,23,4.0,17.0,2.0,6,2.0,0,0
6,BAKSA,GAUTAM RAJBONGSHI,5,0.0,3.0,0.0,2,0.0,0,0
7,BAKSA,GOPIMOHAN BAISHYA,4,0.0,1.0,0.0,2,0.0,0,1
8,BAKSA,IDRISH ALI,7,0.0,5.0,0.0,1,0.0,0,1
9,BAKSA,KARTIK DAS,15,2.0,11.0,1.0,4,1.0,0,0
10,BAKSA,KHAIRUL HUSSAIN,2,0.0,1.0,0.0,1,0.0,0,0
11,BAKSA,MAZAMIL HAQUE,3,0.0,1.0,0.0,2,0.0,0,0
12,BAKSA,MRIDUPABAN DAS,12,0.0,7.0,0.0,5,0.0,0,0
13,BAKSA,NAYAN NATH,16,0.0,11.0,0.0,3,0.0,0,2
14,BAKSA,PINKU KALITA,11,0.0,6.0,0.0,4,0.0,0,1
15,BAKSA,PUNAM BEGUM,10,0.0,5.0,0.0,5,0.0,0,0
16,BAKSA,RAJIB RAMCHIARY,2,0.0,1.0,0.0,1,0.0,0,0
17,BAKSA,SAHID ALI,6,0.0,3.0,0.0,3,0.0,0,0
18,BAKSA,TARUN BISWAS,11,0.0,8.0,0.0,3,0.0,0,0
19,BARPETA,BHARAT DAS,23,3.0,13.0,1.0,10,2.0,0,0
20,BARPETA,DHIRU BARMAN,20,4.0,14.0,2.0,5,1.0,0,1
21,BARPETA,DILDAR KHAN,18,2.0,9.0,0.0,8,2.0,0,1
22,BARPETA,HAFIZUR RAHMAN,22,2.0,16.0,2.0,6,0.0,0,0
23,BARPETA,JULHAS ALI,16,2.0,13.0,1.0,3,1.0,0,0
24,BARPETA,KAMAL DAS,14,3.0,3.0,0.0,8,1.0,0,3
25,BARPETA,KAVITA SINHA,4,0.0,4.0,0.0,0,0.0,0,0
26,BARPETA,LATUMONI BARMAN,1,0.0,0.0,0.0,0,0.0,0,1
27,BARPETA,MAYAN ALI,21,2.0,16.0,2.0,5,0.0,0,0
28,BARPETA,MD UDDIN,22,4.0,5.0,0.0,17,4.0,0,0
29,BARPETA,MINAKHI DAS,4,0.0,4.0,0.0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
386,SHRAWASTI,AMIT MISHRA,16,4.0,3.0,2.0,12,2.0,0,1
387,SHRAWASTI,ANUSHKA SINGH,22,0.0,11.0,0.0,11,0.0,0,0
388,SHRAWASTI,AVINASH MISHRA,10,4.0,2.0,1.0,8,3.0,0,0
389,SHRAWASTI,CHANDAN SHARMA,24,3.0,9.0,1.0,12,1.0,2,1
390,SHRAWASTI,DEENA YADAV,34,3.0,9.0,2.0,21,1.0,0,4
391,SHRAWASTI,DHANEERAM GUPTA,40,4.0,4.0,0.0,34,4.0,1,1
392,SHRAWASTI,DOODH VERMA,34,3.0,13.0,1.0,20,2.0,0,1
393,SHRAWASTI,DWARIKA SHARMA,23,5.0,6.0,1.0,16,4.0,0,1
394,SHRAWASTI,GULSHAN KUMAR,38,5.0,12.0,1.0,24,3.0,0,2
395,SHRAWASTI,KALPANA SHRIVASTAVA,34,4.0,11.0,1.0,21,2.0,1,1
396,SHRAWASTI,KUMAR SRUVASTAVA,28,4.0,9.0,2.0,18,2.0,0,1
397,SHRAWASTI,MOHIT SHARMA,23,4.0,11.0,2.0,11,2.0,0,1
398,SHRAWASTI,MUZAFFAR KHAN,26,1.0,16.0,0.0,10,1.0,0,0
399,SHRAWASTI,NANDINI SINGH,21,2.0,10.0,0.0,11,2.0,0,0
400,SHRAWASTI,PREETI RAV,37,0.0,17.0,0.0,20,0.0,0,0
401,SHRAWASTI,SHIVAM GUPTA,30,3.0,14.0,2.0,16,1.0,0,0
402,SHRAWASTI,SONU,33,3.0,17.0,0.0,15,2.0,0,1
403,SHRAWASTI,VIJAY MISHRA,22,2.0,16.0,2.0,6,0.0,0,0
404,SHRAWASTI,VISHAR KASHAUDHAN,34,1.0,5.0,0.0,29,1.0,0,0
405,SONBHADRA,ABHAY YADAV,15,3.0,6.0,1.0,9,2.0,0,0
406,SONBHADRA,GOVERDHAN YADAV,31,4.0,3.0,1.0,24,3.0,0,4
407,SONBHADRA,KAMLESH KUMAR,34,3.0,6.0,2.0,27,1.0,0,1
408,SONBHADRA,MANNU SETH,25,0.0,10.0,0.0,15,0.0,0,0
409,SONBHADRA,RAHUL YADAV,30,4.0,11.0,2.0,18,2.0,0,1
410,SONBHADRA,RAJESH PANDEY,27,3.0,16.0,2.0,9,1.0,0,2
411,SONBHADRA,RAKESH SHRIWASTAV,21,3.0,11.0,2.0,10,1.0,0,0
412,SONBHADRA,REETA MAURYA,8,4.0,5.0,3.0,3,1.0,0,0
413,SONBHADRA,SADHANA DEVI,18,0.0,13.0,0.0,5,0.0,0,0
414,SONBHADRA,SURENDRA PRAJAPATI,34,5.0,13.0,3.0,18,2.0,1,2
415,SONBHADRA,SURYA SINGH,25,3.0,12.0,1.0,13,2.0,0,0

In [6]:
#widget
#items = sorted(result['dist_name'].unique().tolist())

#def view(District=''):
  #  display(table[table['dist_name']==District])

#w = widgets.Select(options=items)
#v = interactive(view, District=w)
#display(v)

interactive(children=(Select(description='District', options=('ARARIA', 'BAHRAICH', 'BAKSA', 'BALRAMPUR', 'BAR…