In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, MetaData
from sqlalchemy import Integer, String, Float
from sqlalchemy import Column,Integer,Sequence, String, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import psycopg2
import numpy as np
import matplotlib.pyplot as pp
import pandas as pd
import seaborn
import scipy.stats as stats
import pylab as pl

In [31]:
result = pd.read_csv('/Users/ryan/Desktop/baseline/notebook/baseline_data_for_viewer.csv', header=0, dtype= 'unicode', parse_dates=['date'])   
enum_names = pd.read_csv('/Users/ryan/Downloads/enum_list_baseline_MAY17 (Autosaved).csv',header=0, dtype= 'unicode')
result.loc[result['dod_enumerator_id_intro'] == "amirulislamo4416@gmail.com" ,'dod_enumerator_id_intro'] = "amirulislam04416@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "deepakkharte@gmail.com" ,'dod_enumerator_id_intro'] = "deepakkharte14@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "jagdishpawar1983@rediffmail.com" ,'dod_enumerator_id_intro'] = "pawarjagdish1983@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "jagdishpawar1983@rediffmail.com" ,'dod_enumerator_id_intro'] = "pawarjagdish1983@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "kumarvikash5055@gmail.com" ,'dod_enumerator_id_intro'] = "vikashkrsah51@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "kundan9570dod@gmail.com" ,'dod_enumerator_id_intro'] = "kundan957dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "modaser@gmail.com" ,'dod_enumerator_id_intro'] = "modasder@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "rahul.rawelcom@gmail.com" ,'dod_enumerator_id_intro'] = "rahulkumarjha.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "ramesh.chandra@rain-drop.org" ,'dod_enumerator_id_intro'] = "rameshchandra.ssa1980@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "shahmanoj519@gmail" ,'dod_enumerator_id_intro'] = "shahmanoj519@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "tharshit290@gmail.com" ,'dod_enumerator_id_intro'] = "tharshit190@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "wasimansarihrp@gmail.com" ,'dod_enumerator_id_intro'] = "wasimansari.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "Lalitpanwargm@gmail.com" ,'dod_enumerator_id_intro'] = "lalitpanwargm@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "manojmurmu.dod@gmail.co" ,'dod_enumerator_id_intro'] = "manojmurmu.dod@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mdas88644@giml.co" ,'dod_enumerator_id_intro'] = "mdas88644@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mantoshkumar.dod7654@gmil.come" ,'dod_enumerator_id_intro'] = "mantoshkumar.dod7654@gmil.com"

result.loc[result['dod_enumerator_id_intro'] == "jitendrakmr.singh8294@gmail.com0" ,'dod_enumerator_id_intro'] = "jitendrakmr.singh8294@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "ashokkumar.dod96@gmail.comA" ,'dod_enumerator_id_intro'] = "ashokkumar.dod96@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "dilipkumar1993@gmail.come" ,'dod_enumerator_id_intro'] = "dilipkumar1993@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mantoshkumar.dod7654@gmil.com" ,'dod_enumerator_id_intro'] = "mantoshkumar.dod7654@gmail.com"
result.loc[result['dod_enumerator_id_intro'] == "mdas88644@giml.com" ,'dod_enumerator_id_intro'] = "mdas88644@gmail.com"



result = result.merge(enum_names,how='left', on = 'dod_enumerator_id_intro')

In [32]:
table = result[['state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).count()
table['Total Attempted'] = result[['scto_uuid', 'state_name', 'dist_name','enum_name']].groupby(['state_name', 'dist_name','enum_name']).count()
table

                                             Total Attempted
state_name    dist_name enum_name
ASSAM         BAKSA     ASHOK KUMAR                       19
                        ATIKUR RAHMAN                     19
                        CHAMPAK DAS                       14
                        DEEPJYOTI DEKA                    17
                        DIGANTA DAS                       23
                        GAGAN BARMAN                      23
                        GAUTAM RAJBONGSHI                  5
                        GOPIMOHAN BAISHYA                  4
                        IDRISH ALI                         7
                        KARTIK DAS                        15
                        KHAIRUL HUSSAIN                    2
                        MAZAMIL HAQUE                      3
                        MRIDUPABAN DAS                    12
                        NAYAN NATH                        16
                        PINKU KALITA                      11
                        PUNAM BEGUM                       10
                        RAJIB RAMCHIARY                    2
                        SAHID ALI                          6
                        TARUN BISWAS                      11
              BARPETA   BHARAT DAS                        23
                        DHIRU BARMAN                      20
                        DILDAR KHAN                       18
                        HAFIZUR RAHMAN                    22
                        JULHAS ALI                        16
                        KAMAL DAS                         14
                        KAVITA SINHA                       4
                        MAYAN ALI                         21
                        MD UDDIN                          22
                        MINAKHI DAS                        4
                        NUR UDDIN                         21
...                                                      ...
UTTAR PRADESH SHRAWASTI AMIT MISHRA                       16
                        ANUSHKA SINGH                     22
                        AVINASH MISHRA                    10
                        CHANDAN SHARMA                    24
                        DEENA YADAV                       34
                        DHANEERAM GUPTA                   40
                        DOODH VERMA                       34
                        DWARIKA SHARMA                    23
                        GULSHAN KUMAR                     38
                        KALPANA SHRIVASTAVA               34
                        KUMAR SRUVASTAVA                  28
                        MOHIT SHARMA                      23
                        MUZAFFAR KHAN                     26
                        NANDINI SINGH                     21
                        PREETI RAV                        37
                        SHIVAM GUPTA                      30
                        SONU                              33
                        VIJAY MISHRA                      22
                        VISHAR KASHAUDHAN                 34
              SONBHADRA ABHAY YADAV                       15
                        GOVERDHAN YADAV                   31
                        KAMLESH KUMAR                     34
                        MANNU SETH                        25
                        RAHUL YADAV                       30
                        RAJESH PANDEY                     27
                        RAKESH SHRIWASTAV                 21
                        REETA MAURYA                       8
                        SADHANA DEVI                      18
                        SURENDRA PRAJAPATI                34
                        SURYA SINGH                       25

[414 rows x 1 columns]